Repository DKU-SWExpert/SOLID-KPI-FE, pull requests merged in 2024-12, with the labels that each got.

#27 fix(#26): 사용하지 않는 role 변수를 주석처리함
  src/App.tsx
Labels: 👀 frontend, 🐞 bug

#37 fix(#36): 미사용 변수 제거
  src/store/auth.ts
Labels: 👀 frontend, 🐞 bug

#35 feat(#31): 인턴십 결과 입력 페이지 구현
  src/pages/Student/Internship/EnterResult.tsx
Labels: 👀 frontend, 🔥 feat

#41 fix(#40): navigation 경로 수정
  src/routes/StudentRoutes.tsx
Labels: 👀 frontend, 🐞 bug

#47 fix(#45): import 오류 수정
  src/pages/Student/scholarship/SwSupport/index.tsx
  src/pages/Student/scholarship/swExpert/index.tsx
  src/pages/student/scholarship/swExpert/index.tsx
Labels: 👀 frontend, 🐞 bug

#53 refactor(#52): 각 화면의 제목 디자인을 수정한다.
  src/components/Card/Title.tsx
  src/components/Layout/index.tsx
  src/pages/Student/Internship/Application.tsx
  src/pages/Student/Internship/EnterResult.tsx
Labels: 🪜 refactor, 👀 frontend

#55 refactor(background): 색상 변경
  src/components/ApplicationForm/index.tsx
  src/components/AvatarDropdownMenu/index.tsx
  src/components/CommonCard/index.tsx
  src/components/Header/index.tsx
  src/components/Layout/index.tsx
  src/components/MiniHeader/index.tsx
  src/components/Sidebar/index.tsx
  src/components/TestCategory/index.tsx
  src/components/TestDate/index.tsx
  src/components/TestLevel/index.tsx
  src/components/TestScore/index.tsx
  src/components/TestScoreCertification/index.tsx
  src/styles/custom-color.css
Labels: 🪜 refactor, 👀 frontend

#72 feat(#63): [SW 유망주] 페이지 생성
  src/config/navigation.ts
  src/pages/Student/scholarship/SwRisingStar/index.tsx
  src/routes/StudentRoutes.tsx
Labels: 👀 frontend, 🔥 feat
